### ISSUE TITLE
BatchRefine factory & OpenRefine plugin register wrong URI

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-batchrefine#6]
When I register a new BatchRefine configuration via the BatchRefine Factory UI or via the new OpenRefine plugin the URI for the transformer goes wrong. Sample:

    http://playground.fusepool.info:8310?refinejson=http%3A%2F%2Fplayground.fusepool.info%3A8181%2Fldp%2FA-LOD-StABS-Helvetik-20141223-json.json

Note the missing `/`before `?refinejson...`

This does lead to problems in pipelines, where the request will fail. It does work in the test-UI though, I suspect the browser is fixing the wrong URI.

**Comment by andreybratus** [comment]
This issue is more suitable for the openrefine-extension for P3, which is a separate repository: [p3-openrefine-extension](https://github.com/fusepoolP3/p3-openrefine-extension)

1. However, this [commit](https://github.com/fusepoolP3/p3-openrefine-extension/commit/7337c61e3d957941913a411e2bcc0f590f3bc450)  closes the issue.
2. OpenRefine, bundled with the fixed extension has been released: [OpenRefine 2.6-p3 release](https://github.com/fusepoolP3/OpenRefine/releases/tag/2.6-p3)
3. Docker image: **fusepool/openrefine** [build](https://hub.docker.com/r/fusepool/openrefine/builds/b7yphjoqr8geseslcndfydb/)

**Comment by ktk** [comment]
Yay thanks @andreybratus !
